settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: stream-wrench-gq # unique identifier
    name: File Stream Server
    description: 'Server of FileStreamBot.' # default=empty
    url: 'https://stream.wrench.gq/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: blog-wrench-gq
    name: Blog
    description: 'Pretty much empty.'
    url: 'https://blog.wrench.gq'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: telegram-api
    name: Telegram API
    url: 'https://api.telegram.org'
    method: GET
    expectStatus: 200
